### ISSUE TITLE
We can make a new product which replaces github, open source, and the hosting costs can be shared

### ISSUE THREAD

**Issue by cooldesigns** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#36] opened 2018-06-04 19:16 UTC
We can find a method for share hosting costs: Example ideas:
- Calculating user's hosting cost and invoicing unless the cost will be bigger than 1$
- Decentralize hosting. Using serverless. Like spotify.
- Donation on open collective
- The super idea: Make a feature: Allow users to donate to open source software and get commission for hosting costs.

Software is basic for us. We can develop gags, and we can make it's features more social. It's already ready and stable.

**Comment by vassudanagunta** [comment] 2018-06-04 19:18
Thank you! But this is a duplicate of #25. Please copy your ideas there.

**Closed by vassudanagunta** 2018-06-04 19:18 UTC

**Comment by vassudanagunta** [comment] 2018-06-16 08:44
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
